# Mecanum drive controller configuration for Sherpa
sherpa_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

sherpa_mecanum_controller:
  type: "mecanum_drive_controller/MecanumDriveController"
  front_left_wheel_joint: "LF_WHEEL_JOINT"
  front_right_wheel_joint: "RF_WHEEL_JOINT"
  rear_left_wheel_joint: "LH_WHEEL_JOINT" 
  rear_right_wheel_joint: "RH_WHEEL_JOINT"
  publish_rate: 50
  pose_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.3]
  twist_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.3]
  cmd_vel_timeout: 0.25
  velocity_rolling_window_size: 2
  enable_odom_tf: false

  # Wheel geometry
  wheel_separation_x: 0.4318  # Distance between front and rear wheels
  wheel_separation_y: 0.47    # Distance between left and right wheels
  wheel_radius: 0.19         # Wheel radius

gazebo_ros_control:
  pid_gains:
    LF_WHEEL_JOINT:
      p: 100.0
    RF_WHEEL_JOINT:
      p: 100.0
    LH_WHEEL_JOINT:
      p: 100.0
    RH_WHEEL_JOINT:
      p: 100.0

  # Base frame_id
  base_frame_id: base_link

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.1   # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0   # m/s^2
    y:
      has_velocity_limits    : true
      max_velocity           : 1.1   # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 3.0   # rad/s^2
